# This workflow builds and checks the package for release
name: Build

on:
  pull_request:
    # Check all PR

jobs:
  build:
    if: github.repository == 'NMRLipids/Databank'
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - run: pip install tox

    - name: Test build integrity
      run: tox -e build
