# Check if all systems in the NMRlipids databank contain an unique ID and
# if a search for compatible experiments has been conducted
#
# Contact:
#  Fabián Suárez-Lestón
#  fabian.suarez.leston@usc.es

name: CheckSystems

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events, but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    paths: ['Data/Simulations/**']
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "TestNewSystems"
  TestNewSystems:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Check IDs
        id: checkids
        run: |
          . .github/workflows/CheckIDs.sh

      - name: Check Experiments
        id: checkexps
        run: |
          . .github/workflows/CheckExperiments.sh
