name: Weekly Scheduled Tests

on:
  schedule:
    # Runs every Monday at 12:00 UTC
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  regression-tests:
    if: github.repository == 'NMRLipids/Databank'
    runs-on: ubuntu-latest
    container:
      image: nmrlipids/core
      options: --user 1001:118
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Run regression test suite
        run: ./runtests-regression.sh